### ISSUE TITLE
v2.4 installation error: No medatada file in package

### ISSUE THREAD

**Issue by k0nk** [nclarius/KWin-window-positioning-scripts#8]
Hi, I'm trying to install your script but this error popped up:

![image](https://user-images.githubusercontent.com/58905143/154119767-8da1af88-3ba3-4a81-aad7-caa81766f74f.png)

**Comment by nclarius** [comment]
Thanks; it should be fixed now; please confirm that the most recent version works.

**Comment by k0nk** [comment]
Unfortunately it's still happening and the error message is slightly different:
![image](https://user-images.githubusercontent.com/58905143/154371280-c3e91fd0-f494-405c-aa6b-bf2564974eba.png)

**Comment by nclarius** [comment]
Ok; try again with the newest version.

**Comment by k0nk** [comment]
Now it worked. Thank you!
